apiVersion: v1
kind: Service
metadata:
  name: pedido-service
  namespace: casa-dos-farelos

spec:
  selector:
    app: pedido-service

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP